services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kosmanager-app
    restart: unless-stopped
    network_mode: "host"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--dns-result-order=ipv4first
      - NUXT_AUTH_SECRET=${AUTH_SECRET}
      - NUXT_DATABASE_URL=${DATABASE_MIGRATE_URL}
      - NUXT_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - NUXT_GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NUXT_PUBLIC_AUTH_ORIGIN=${AUTH_ORIGIN}
      - AUTH_ORIGIN=${AUTH_ORIGIN}
      - NEXTAUTH_URL=${AUTH_ORIGIN}