services:
  playwright:
    image: mcr.microsoft.com/playwright:v1.61.0-jammy
    container_name: kosmanager-e2e
    # Use host network to allow the container to access http://localhost:3000 where Nuxt is running
    network_mode: "host"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - CI=true
    # Install npm dependencies then run Playwright
    command: >
      bash -c "npm install --ignore-scripts && npx playwright test"
